

# This file was *autogenerated* from the file /mnt/c/git/oicc2026/crypto/baby-shark/solution/solve_babyshark.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_256 = Integer(256); _sage_const_128 = Integer(128); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_22 = Integer(22); _sage_const_7 = Integer(7); _sage_const_16 = Integer(16); _sage_const_2 = Integer(2); _sage_const_6004 = Integer(6004)
from pwn import *
from hashlib import sha256
import ast

p = (_sage_const_3  << _sage_const_256 ) - (_sage_const_3  << _sage_const_128 ) + _sage_const_1 
E  = EllipticCurve(GF(p), [_sage_const_0 , _sage_const_22 ])
G  = E(_sage_const_3 , _sage_const_7 )
z1, z2 = [int(sha256(m).hexdigest(),_sage_const_16 ) for m in (b"Baby shark", b"Doo doo doo doo doo doo")]

def getQ(sig, z):
    r, s = map(GF(p), sig)
    for R in E.lift_x(r, all=True):
        yield (s * R - z * G) / r

def smart_dlog(P, Q):
    E2 = EllipticCurve(Zmod(p**_sage_const_2 ), [p, _sage_const_22 ])
    P2 = E2.lift_x(ZZ(P[_sage_const_0 ]))
    Q2 = E2.lift_x(ZZ(Q[_sage_const_0 ]))
    dlog = mod(ZZ((p*Q2)[_sage_const_0 ])/ZZ((p*P2)[_sage_const_0 ]), p)
    return [-dlog,dlog][dlog*P==Q]

with remote('challenges.oceaniacc.com', _sage_const_6004 ) as io:
    io.readuntil(b': '); sig1 = ast.literal_eval(io.readline().decode())
    io.readuntil(b': '); sig2 = ast.literal_eval(io.readline().decode())

    Q = (set(getQ(sig1, z1)) & set(getQ(sig2, z2))).pop()
    d = smart_dlog(G, Q)
    r = -(z1 + z2) / (_sage_const_2  * d)
    k = smart_dlog(G, E.lift_x(r))
    s = (z1 + r * d) / k

    io.sendline(f'{r,s}'.encode())
    print(io.readall())

